build: Add explicit wayland-client dependency
This should fix this issue that happens after commit 5151250d9433f978429cf7572b5159394c082355:
src/gamescope.p/main.cpp.o: undefined reference to symbol 'wl_display_connect'

Thanks to PedroHLC for reporting it on Discord 🐸